
package com.example.taxgap.service; import com.example.taxgap.domain.entity.*; import com.example.taxgap.domain.enums.*; import com.example.taxgap.repository.*; import com.fasterxml.jackson.databind.*; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.util.*;
@Service public class RuleEngineService { private final TaxRuleRepository ruleRepo; private final ExceptionService exceptionService; private final AuditLogService audit; private final ObjectMapper mapper; private final FinancialTransactionRepository txnRepo; public RuleEngineService(TaxRuleRepository r, ExceptionService e, AuditLogService a, ObjectMapper m, FinancialTransactionRepository t){ruleRepo=r;exceptionService=e;audit=a;mapper=m;txnRepo=t;}
  public void executeAll(FinancialTransaction ft){ for(TaxRule rule: ruleRepo.findByEnabledTrue()){ try{ switch(rule.getType()){ case "HIGH_VALUE" -> highValue(ft,rule); case "REFUND_VALIDATION" -> refundValidation(ft,rule); case "GST_SLAB" -> gstSlab(ft,rule); default -> {} } audit.log(EventType.RULE_EXECUTION, ft.getTransactionId(), "Executed rule: "+rule.getName()); } catch(Exception ex){ exceptionService.create(ft.getTransactionId(), ft.getCustomerId(), rule.getName(), Severity.HIGH, "Rule error: "+ex.getMessage()); } } }
  private void highValue(FinancialTransaction ft, TaxRule rule) throws Exception { JsonNode cfg=mapper.readTree(rule.getConfigJson()); BigDecimal threshold=cfg.path("threshold").decimalValue(); if(ft.getAmount().compareTo(threshold)>0) exceptionService.create(ft.getTransactionId(), ft.getCustomerId(), rule.getName(), rule.getSeverity(), "Amount exceeds threshold: "+threshold); }
  private void refundValidation(FinancialTransaction ft, TaxRule rule) throws Exception { if(ft.getTransactionType()!=TransactionType.REFUND) return; JsonNode cfg=mapper.readTree(rule.getConfigJson()); int fallbackDays=cfg.path("fallbackDays").asInt(180); BigDecimal refundAmt=ft.getAmount().abs(); if(ft.getOriginalSaleTransactionId()!=null && !ft.getOriginalSaleTransactionId().isBlank()){ Optional<FinancialTransaction> saleOpt=txnRepo.findByTransactionId(ft.getOriginalSaleTransactionId()); if(saleOpt.isPresent()){ BigDecimal saleAmt=saleOpt.get().getAmount(); if(refundAmt.compareTo(saleAmt)>0) exceptionService.create(ft.getTransactionId(), ft.getCustomerId(), rule.getName(), rule.getSeverity(), String.format("Refund %.2f > original sale %.2f", refundAmt, saleAmt)); return; } }
    List<FinancialTransaction> recentSales=txnRepo.findRecentByCustomerAndType(ft.getCustomerId(), TransactionType.SALE); LocalDate cutoff=ft.getDate().minusDays(fallbackDays); for(FinancialTransaction s: recentSales){ if(!s.getDate().isBefore(cutoff)){ BigDecimal saleAmt=s.getAmount(); if(refundAmt.compareTo(saleAmt)>0) exceptionService.create(ft.getTransactionId(), ft.getCustomerId(), rule.getName(), rule.getSeverity(), String.format("Refund %.2f > recent sale %.2f (fallback %d days)", refundAmt, saleAmt, fallbackDays)); break; } } }
  private void gstSlab(FinancialTransaction ft, TaxRule rule) throws Exception { JsonNode cfg=mapper.readTree(rule.getConfigJson()); JsonNode slabs=cfg.path("slabs"); BigDecimal amt=ft.getAmount(); BigDecimal rate=ft.getTaxRate(); for(JsonNode slab: slabs){ BigDecimal min=slab.path("min").decimalValue(); JsonNode maxNode=slab.path("max"); BigDecimal max=maxNode.isNull()?null:maxNode.decimalValue(); BigDecimal required=slab.path("rate").decimalValue(); boolean inRange=(amt.compareTo(min)>=0) && (max==null || amt.compareTo(max)<0); if(inRange && rate.compareTo(required)<0){ exceptionService.create(ft.getTransactionId(), ft.getCustomerId(), rule.getName(), rule.getSeverity(), String.format("Tax rate %.4f below required slab %.4f for amount %s", rate, required, amt)); break; } } }
}
